import Foundation

// BrokerdSettings — TOML config loader for the broker daemon.
//
// W4.1 of spec e8c4a921-7d3b-4f5e-9a2c-1d6b8f4e3a91
//
// Loads from ~/.shikki/settings/secrets-brokerd.toml using the same
// hand-parsing pattern as Bootstrap.readVaultURLFromTOML (no SPM deps).
//
// Config file shape:
//
//   vault_url = "https://vw.example.com"
//
//   [scope]
//   # Glob patterns allowed for secret.get requests.
//   # Empty list (the default) DENIES all reads.
//   # "**" matches anything (DEV ONLY — never use in production).
//   allowlist = ["**"]
//
// Config-chain for scopeAllowlist (highest priority first):
//   1. Explicit TOML file path (test injection via loadOrDefault(from:))
//   2. Default path ~/.shikki/settings/secrets-brokerd.toml
//   3. Fallback: ["**"] (dev-friendly, logged as WARN)
//
// Note: vaultURL is also extracted here for future migration of
// Bootstrap.readVaultURLFromTOML into this consolidated type.
// For now, Bootstrap continues to use its own reader for compatibility.

public struct BrokerdSettings: Sendable, Equatable {

    // MARK: - Properties

    /// Optional override for the Vaultwarden server URL.
    /// `nil` means: fall through to the Bootstrap config-chain.
    public let vaultURL: URL?

    /// Glob patterns allowed for `secret.get` requests.
    /// Empty list means deny-all reads. `["**"]` is the dev-friendly default.
    public let scopeAllowlist: [String]

    // MARK: - Init

    public init(scopeAllowlist: [String], vaultURL: URL?) {
        self.scopeAllowlist = scopeAllowlist
        self.vaultURL = vaultURL
    }

    // MARK: - Convenience

    /// True when the allowlist is exactly `["**"]` — the dev-mode wildcard.
    /// Used by Main.swift to emit a WARN about the prod alternative.
    public var isWildcardAllowlist: Bool {
        scopeAllowlist == ["**"]
    }

    // MARK: - TOML loading

    /// Load settings from a TOML file at `path`.
    ///
    /// - Throws: `BrokerdSettingsError.malformedTOML` when the file content
    ///   is syntactically invalid (e.g. unclosed section header, unterminated
    ///   array).
    /// - Returns: parsed settings; `scopeAllowlist` is `[]` when `[scope]`
    ///   section is absent.
    public static func load(from path: URL) throws -> BrokerdSettings {
        guard let text = try? String(contentsOf: path, encoding: .utf8) else {
            throw BrokerdSettingsError.malformedTOML(reason: "Could not read file at \(path.path)")
        }
        return try parse(toml: text)
    }

    /// Load settings from `path`, returning dev-friendly defaults when the
    /// file is absent.
    ///
    /// - Parameter path: TOML file URL. When the file does not exist,
    ///   returns `BrokerdSettings(scopeAllowlist: ["**"], vaultURL: nil)`.
    public static func loadOrDefault(from path: URL) -> BrokerdSettings {
        guard FileManager.default.fileExists(atPath: path.path) else {
            return BrokerdSettings(scopeAllowlist: ["**"], vaultURL: nil)
        }
        do {
            return try load(from: path)
        } catch {
            // Malformed file → fall through to safe dev default.
            return BrokerdSettings(scopeAllowlist: ["**"], vaultURL: nil)
        }
    }

    /// Load from the canonical default path `~/.shikki/settings/secrets-brokerd.toml`.
    public static func loadOrDefault(homeDirectory: String = NSHomeDirectory()) -> BrokerdSettings {
        let path = (homeDirectory as NSString)
            .appendingPathComponent(".shikki/settings/secrets-brokerd.toml")
        return loadOrDefault(from: URL(fileURLWithPath: path))
    }

    /// Write a dev-seed config file at `path` if and only if the file does
    /// not already exist. The written file contains a `[scope] allowlist = ["**"]`
    /// entry plus explanatory comments.
    ///
    /// This is idempotent: calling it on an existing file is a no-op.
    public static func writeDefaultIfMissing(at path: URL) throws {
        guard !FileManager.default.fileExists(atPath: path.path) else {
            return // no-op — do not overwrite operator-customized config
        }
        let defaultContent = """
            # secrets-brokerd configuration
            # Generated by shikki-secrets-brokerd on first boot.
            # Edit this file to customize behavior.
            #
            # vault_url = "https://vw.example.com"

            [scope]
            # Glob patterns allowed for secret.get requests.
            # Empty list DENIES all reads; secret.set and secret.list still work.
            # "**" matches anything — DEV ONLY. Never use in production.
            # Production examples: "shi/**", "ci/**", "verify-*"
            allowlist = ["**"]
            """
        try defaultContent.write(to: path, atomically: true, encoding: .utf8)
    }

    // MARK: - Hand-parser (intentionally minimal — same pattern as Bootstrap.readVaultURLFromTOML)

    /// Parse a minimal TOML subset: top-level key = value, [section], array values.
    ///
    /// Supported shapes:
    ///   - `key = "value"` (quoted strings)
    ///   - `[section]`
    ///   - `key = ["item1", "item2"]` (string arrays, single-line only)
    ///   - `# comment` (ignored)
    ///   - Blank lines (ignored)
    ///
    /// Multi-line arrays are NOT supported by this parser. If a line contains
    /// an unclosed `[` in the section header position, it throws malformedTOML.
    static func parse(toml text: String) throws -> BrokerdSettings {
        var currentSection: String? = nil
        var scopeAllowlist: [String] = []
        var vaultURL: URL? = nil

        let lines = text.components(separatedBy: "\n")
        for rawLine in lines {
            let line = rawLine.trimmingCharacters(in: .whitespaces)

            // Skip blank and comment lines
            if line.isEmpty || line.hasPrefix("#") { continue }

            // Section header: [section-name]
            if line.hasPrefix("[") {
                guard line.hasSuffix("]") else {
                    throw BrokerdSettingsError.malformedTOML(
                        reason: "Unclosed section header: \(line)"
                    )
                }
                currentSection = String(line.dropFirst().dropLast()).trimmingCharacters(in: .whitespaces)
                continue
            }

            // Key = value
            guard let eqIdx = line.firstIndex(of: "=") else { continue }
            let key = line[..<eqIdx].trimmingCharacters(in: .whitespaces)
            let rawValue = line[line.index(after: eqIdx)...].trimmingCharacters(in: .whitespaces)

            if currentSection == "scope" && key == "allowlist" {
                scopeAllowlist = try parseStringArray(rawValue)
            } else if currentSection == nil && key == "vault_url" {
                let stripped = stripQuotes(rawValue)
                if !stripped.isEmpty, let url = URL(string: stripped) {
                    vaultURL = url
                }
            }
        }

        return BrokerdSettings(scopeAllowlist: scopeAllowlist, vaultURL: vaultURL)
    }

    /// Parse a single-line TOML string array: `["foo", "bar", "baz"]`.
    private static func parseStringArray(_ raw: String) throws -> [String] {
        var s = raw.trimmingCharacters(in: .whitespaces)
        guard s.hasPrefix("[") else {
            throw BrokerdSettingsError.malformedTOML(reason: "Expected array starting with '[', got: \(s)")
        }
        guard s.hasSuffix("]") else {
            throw BrokerdSettingsError.malformedTOML(reason: "Unclosed array (multi-line not supported): \(s)")
        }
        // Drop surrounding [ ]
        s = String(s.dropFirst().dropLast()).trimmingCharacters(in: .whitespaces)
        if s.isEmpty { return [] }

        // Split on commas, strip quotes from each element
        var result: [String] = []
        for part in s.components(separatedBy: ",") {
            let elem = part.trimmingCharacters(in: .whitespaces)
            if elem.isEmpty { continue }
            let stripped = stripQuotes(elem)
            result.append(stripped)
        }
        return result
    }

    /// Strip surrounding `"..."` or `'...'` from a TOML string value.
    private static func stripQuotes(_ s: String) -> String {
        var r = s
        if (r.hasPrefix("\"") && r.hasSuffix("\"")) ||
           (r.hasPrefix("'") && r.hasSuffix("'")) {
            r = String(r.dropFirst().dropLast())
        }
        return r
    }
}

// MARK: - Errors

public enum BrokerdSettingsError: Swift.Error, Sendable, Equatable {
    /// The TOML file is syntactically invalid.
    case malformedTOML(reason: String)
}
